[versions]
agp = "8.7.3"
desugar_jdk_libs = "2.1.5"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
materialSpinner = "1.3.1"
materialVersion = "1.1.0"
pinview = "1.4.4"
retrofit = "2.9.0"

[libraries]
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
cardview = { group = "androidx.cardview", name = "cardview", version = "1.0.0"}
material-spinner = { module = "com.jaredrummler:material-spinner", version.ref = "materialSpinner" }
material-v110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
pinview = { module = "io.github.chaosleung:pinview", version.ref = "pinview" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.4.0"}
circleindicator = { group = "me.relex", name = "circleindicator", version = "2.1.6"}
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { group = "com.github.bumptech.glide", name = "glide", version = "4.16.0"}
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

